rpc:
    mainnet:
        uri: https://mainnet.tezos.org.ua
        timeout: 20
    zeronet:
        uri: https://rpc.tzkt.io/zeronet
        timeout: 20
    babylonnet:
        uri: https://babylontest-ssl.tezos.org.ua
        timeout: 20
    carthagenet:
        uri: https://carthatest-ssl.tezos.org.ua
        timeout: 20
    sandboxnet:
        uri: http://sandbox:8732
        timeout: 10

tzkt:
    mainnet:
        uri: https://api.tzkt.io/v1/
        timeout: 20
    zeronet:
        uri: https://api.zeronet.tzkt.io/v1/
        timeout: 20
    babylonnet:
        uri: https://api.babylon.tzkt.io/v1/
        timeout: 20
    carthagenet:
        uri: https://api.carthage.tzkt.io/v1/
        timeout: 20

share:
    path: /etc/bcd

sentry:
    environment: production
    uri: ${SENTRY_DSN}
    debug: false

elastic:
    uri: http://127.0.0.1:9200

rabbitmq:
    uri: "amqp://${RABBIT_USER}:${RABBIT_PASSWORD}@127.0.0.1:5672/"
    queues:
        - operations
        - contracts
        - migrations
        - recalc

db:
    conn_string: "host=127.0.0.1 port=5432 user=${POSTGRES_USER} dbname=bcd password=${POSTGRES_PASSWORD} sslmode=disable"

oauth:
    state: ${OAUTH_STATE_STRING}
    jwt:
        secret: ${JWT_SECRET_KEY}
        redirect_url: https://you.better-call.dev/
    github:
        client_id: ${GITHUB_CLIENT_ID}
        secret: ${GITHUB_CLIENT_SECRET}
        callback_url: https://api.better-call.dev/v1/oauth/github/callback
    gitlab:
        client_id: ${GITLAB_CLIENT_ID}
        secret: ${GITLAB_CLIENT_SECRET}
        callback_url: https://api.better-call.dev/v1/oauth/gitlab/callback

api:
    bind: ":14000"
    oauth:
        enabled: true
    sentry:
        enabled: true
        project: api
    networks:
        - mainnet
        - carthagenet
        - zeronet
        - babylonnet

indexer:
    sentry:
        enabled: true
        project: indexer
    networks:
        - network: mainnet
          boost: tzkt
        - network: carthagenet
          boost: tzkt
        - network: zeronet
          boost: tzkt

metrics:
    sentry:
        enabled: true
        project: metrics

aws:
    bucket_name: bcd-elastic-snapshots
    region: eu-central-1
    access_key_id: ${AWS_ACCESS_KEY_ID}
    secret_access_key: ${AWS_SECRET_ACCESS_KEY}